### PR TITLE
Upgrade VADR to v1.2

### PR DESCRIPTION
**Pull request by kislyuk**
Added new config variable `VADRFASTADIR`. Installed "fasta" package (https://faculty.virginia.edu/wrpearson/fasta) via `apt-get install fasta3`.

### CODE REVIEW

**Comment by kislyuk** [comment]
VADR needs new config in: https://github.com/chanzuckerberg/idseq-workflows/pull/108/checks?check_run_id=2433646737#step:5:1733

**Comment by kislyuk** [comment]
Note: I have observed non-determinism in the tests (“no reads after MakeConsensus” disappeared upon re-run). This could be happening due to either concurrent execution of the tests, or non-determinism in the CG workflow code.

**Comment by jshoe** [comment]
@katrinakalantar @morsecodist ?

**Review by katrinakalantar — APPROVED** [review]
This looks good to me.

**Pull request merged**
